In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import json

DATA_PATH = "/content/drive/MyDrive/ApnaHireAI/data/candidates.jsonl"

candidates = []

with open(DATA_PATH, "r", encoding="utf-8") as f:

    for line in f:

        candidates.append(
            json.loads(line)
        )

print(
    "Total Candidates:",
    len(candidates)
)

Total Candidates: 100000

In [3]:
candidate = candidates[0]

print(candidate.keys())

dict_keys(['candidate_id', 'profile', 'career_history', 'education', 'skills', 'certifications', 'languages', 'redrob_signals'])

In [4]:
print(candidate["profile"])

{'anonymized_name': 'Ira Vora', 'headline': 'Backend Engineer | SQL, Spark, Cloud', 'summary': "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.", 'location': 'Toronto', 'country': 'Canada', 'years_of_experience': 6.9, 'current_title': 'Backend Engineer', 'current_company': 'Mindtree', 'current_company_size': '10001+', 'current_industry': 'IT Services'}

In [5]:
print(candidate["skills"][:5])

[{'name': 'Tailwind', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 13}, {'name': 'NLP', 'proficiency': 'advanced', 'endorsements': 37, 'duration_months': 26}, {'name': 'Image Classification', 'proficiency': 'advanced', 'endorsements': 7, 'duration_months': 40}, {'name': 'Fine-tuning LLMs', 'proficiency': 'advanced', 'endorsements': 21, 'duration_months': 36}, {'name': 'Weights & Biases', 'proficiency': 'intermediate', 'endorsements': 13, 'duration_months': 30}]

In [6]:
print(candidate["career_history"][:2])

[{'company': 'Mindtree', 'title': 'Backend Engineer', 'start_date': '2024-03-08', 'end_date': None, 'duration_months': 27, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.'}, {'company': 'Dunder Mifflin', 'title': 'Analytics Engineer', 'start_date': '2019-07-03', 'end_date': '2024-01-08', 'duration_months': 55, 'is_current': False, 'industry': 'Paper Products', 'company_size': '201-500', 'description': 'Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.'}]

In [7]:
print(candidate["redrob_signals"])

{'profile_completeness_score': 86.9, 'signup_date': '2025-10-16', 'last_active_date': '2026-05-20', 'open_to_work_flag': True, 'profile_views_received_30d': 23, 'applications_submitted_30d': 2, 'recruiter_response_rate': 0.34, 'avg_response_time_hours': 177.8, 'skill_assessment_scores': {'NLP': 38.8, 'Image Classification': 64.8, 'Fine-tuning LLMs': 41.6, 'Speech Recognition': 53.7}, 'connection_count': 356, 'endorsements_received': 35, 'notice_period_days': 60, 'expected_salary_range_inr_lpa': {'min': 18.7, 'max': 36.1}, 'preferred_work_mode': 'onsite', 'willing_to_relocate': False, 'github_activity_score': 9.2, 'search_appearance_30d': 249, 'saved_by_recruiters_30d': 4, 'interview_completion_rate': 0.71, 'offer_acceptance_rate': 0.58, 'verified_email': True, 'verified_phone': True, 'linkedin_connected': False}

In [8]:
!pip install sentence-transformers
!pip install pandas
!pip install numpy

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.10.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.17.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [9]:
def create_candidate_text(candidate):

    headline = candidate["profile"].get(
        "headline",
        ""
    )

    summary = candidate["profile"].get(
        "summary",
        ""
    )

    skills = " ".join([
        skill["name"]
        for skill in candidate["skills"]
    ])

    career = " ".join([
        job["description"]
        for job in candidate["career_history"]
    ])

    education = " ".join([
        edu["field_of_study"]
        for edu in candidate["education"]
    ])

    return f"""
    {headline}

    {summary}

    Skills:
    {skills}

    Career:
    {career}

    Education:
    {education}
    """

In [10]:
text = create_candidate_text(
    candidates[0]
)

print(text[:2000])

    Backend Engineer | SQL, Spark, Cloud

    Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.

    Skills:
    Tailwind NLP Image Classification Fine-tuning LLMs Weights & Biases Speech Recognition Photoshop TTS LoRA Apache Beam AWS Flask BentoML Milvus GANs Statistical Modeling GCP

    Career:
    Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure. Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.

    Education:
    Computer Science

In [11]:
candidate_features = []

for candidate in candidates:

    candidate_features.append({

        "candidate_id":
        candidate["candidate_id"],

        "candidate_text":
        create_candidate_text(
            candidate
        ),

        "experience":
        candidate["profile"][
            "years_of_experience"
        ],

        "open_to_work":
        candidate["redrob_signals"][
            "open_to_work_flag"
        ],

        "github_score":
        candidate["redrob_signals"][
            "github_activity_score"
        ],

        "response_rate":
        candidate["redrob_signals"][
            "recruiter_response_rate"
        ]
    })

In [12]:
print(
    candidate_features[0]
)

{'candidate_id': 'CAND_0000001', 'candidate_text': "\n    Backend Engineer | SQL, Spark, Cloud\n\n    Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.\n\n    Skills:\n    Tailwind NLP Image Classification Fine-tuning LLMs Weights & Biases Speech Recognition Photoshop TTS LoRA Apache Beam AWS Flask BentoML Milvus GANs Statistical Modeling GCP\n\n    Career:\n    Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure. Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.\n\n    Education:\n    Computer Science\n    ", 'experience': 6.9, 'open_to_work': True, 'github_score': 9.2, 'response_rate': 0.34}

In [13]:
import os

os.makedirs(
    "/content/drive/MyDrive/ApnaHireAI/output",
    exist_ok=True
)

In [14]:
import pandas as pd

df = pd.DataFrame(
    candidate_features
)

df.to_csv(
    "/content/drive/MyDrive/ApnaHireAI/output/features.csv",
    index=False
)

In [15]:
print(df.columns)

Index(['candidate_id', 'candidate_text', 'experience', 'open_to_work',
       'github_score', 'response_rate'],
      dtype='object')

In [16]:
print(df["candidate_text"].head())

0    \n    Backend Engineer | SQL, Spark, Cloud\n\n...
1    \n    Operations Manager | 12.5+ yrs experienc...
2    \n    Customer Support | 1.1+ yrs experience\n...
3    \n    Marketing Manager | Driving business out...
4    \n    Accountant | Helping teams scale\n\n    ...
Name: candidate_text, dtype: object

In [17]:
print(df["candidate_text"].iloc[0])

    Backend Engineer | SQL, Spark, Cloud

    Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.

    Skills:
    Tailwind NLP Image Classification Fine-tuning LLMs Weights & Biases Speech Recognition Photoshop TTS LoRA Apache Beam AWS Flask BentoML Milvus GANs Statistical Modeling GCP

    Career:
    Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure. Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.

    Education:
    Computer Science

In [18]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.10.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.17.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [19]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [20]:
model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Model Loaded")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Model Loaded

In [21]:
job_description = """
Senior AI Engineer

Production experience with embeddings
Vector databases
Hybrid search
Retrieval systems
Ranking systems
Python

Evaluation Metrics:
NDCG
MRR
MAP

5-9 years experience

Product company experience

Fine-tuning
LoRA
Learning to Rank

Pune
Noida
"""

In [22]:
jd_embedding = model.encode(
    job_description
)

In [23]:
# df = df.sample(
#     10000,
#     random_state=42
# )

In [24]:
candidate_texts = df[
    "candidate_text"
].tolist()

print(
    "Total Candidate Texts:",
    len(candidate_texts)
)

Total Candidate Texts: 100000

In [25]:
candidate_embeddings = model.encode(
    candidate_texts,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

scores = cosine_similarity(
    [jd_embedding],
    candidate_embeddings
)[0]

In [27]:
df["semantic_score"] = scores

print(
    df[
        [
            "candidate_id",
            "semantic_score"
        ]
    ].head()
)

   candidate_id  semantic_score
0  CAND_0000001        0.380332
1  CAND_0000002        0.478619
2  CAND_0000003        0.444468
3  CAND_0000004        0.451939
4  CAND_0000005        0.346960

In [28]:
semantic_df = df.sort_values(
    by="semantic_score",
    ascending=False
)

semantic_df.head(10)

,candidate_id,candidate_text,experience,open_to_work,github_score,response_rate,semantic_score
99805,CAND_0099806,"\n AI Engineer | Search, Ranking & Retrieva...",4.6,True,86.9,0.76,0.714797
61264,CAND_0061265,\n Recommendation Systems Engineer | Search...,6.6,True,79.8,0.94,0.675921
76250,CAND_0076251,"\n Search Engineer | Search, Ranking & Retr...",7.6,True,-1.0,0.51,0.672331
36436,CAND_0036437,"\n Search Engineer | Search, Ranking & Retr...",4.8,False,35.2,0.87,0.667668
45249,CAND_0045250,"\n Applied ML Engineer | Search, Ranking & ...",6.6,False,-1.0,0.74,0.667596
55991,CAND_0055992,"\n AI Engineer | Search, Ranking & Retrieva...",16.9,True,65.3,0.72,0.665302
65194,CAND_0065195,"\n Search Engineer | Search, Ranking & Retr...",5.1,True,87.3,0.80,0.664490
55904,CAND_0055905,"\n Senior Machine Learning Engineer | LLMs,...",8.1,True,-1.0,0.87,0.663254
49537,CAND_0049538,"\n Applied ML Engineer | Search, Ranking & ...",5.8,False,90.8,0.72,0.662527
70201,CAND_0070202,"\n Machine Learning Engineer | Search, Rank...",5.1,False,-1.0,0.60,0.661896

In [29]:
semantic_df[
    [
        "candidate_id",
        "semantic_score",
        "experience"
    ]
].head(20)

       candidate_id  semantic_score  experience
99805  CAND_0099806        0.714797         4.6
61264  CAND_0061265        0.675921         6.6
76250  CAND_0076251        0.672331         7.6
36436  CAND_0036437        0.667668         4.8
45249  CAND_0045250        0.667596         6.6
55991  CAND_0055992        0.665302        16.9
65194  CAND_0065195        0.664490         5.1
55904  CAND_0055905        0.663254         8.1
49537  CAND_0049538        0.662527         5.8
70201  CAND_0070202        0.661896         5.1
41609  CAND_0041610        0.655176         6.7
64325  CAND_0064326        0.655090         7.6
18721  CAND_0018722        0.652239         6.6
69904  CAND_0069905        0.650917         6.6
6556   CAND_0006557        0.649626         7.9
64269  CAND_0064270        0.646239         4.2
40886  CAND_0040887        0.645981         4.7
77336  CAND_0077337        0.645365         7.0
92244  CAND_0092245        0.645122         4.1
71973  CAND_0071974        0.640586         7.8

In [30]:
print(
    semantic_df.head(5)
)

       candidate_id                                     candidate_text  \
99805  CAND_0099806  \n    AI Engineer | Search, Ranking & Retrieva...
61264  CAND_0061265  \n    Recommendation Systems Engineer | Search...
76250  CAND_0076251  \n    Search Engineer | Search, Ranking & Retr...
36436  CAND_0036437  \n    Search Engineer | Search, Ranking & Retr...
45249  CAND_0045250  \n    Applied ML Engineer | Search, Ranking & ...

       experience  open_to_work  github_score  response_rate  semantic_score
99805         4.6          True          86.9           0.76        0.714797
61264         6.6          True          79.8           0.94        0.675921
76250         7.6          True          -1.0           0.51        0.672331
36436         4.8         False          35.2           0.87        0.667668
45249         6.6         False          -1.0           0.74        0.667596

In [31]:
def calculate_behavior_score(row):

    score = 0

    # Open to work
    if row["open_to_work"]:
        score += 30

    # GitHub Activity
    github = row["github_score"]

    if github > 80:
        score += 30

    elif github > 60:
        score += 20

    elif github > 40:
        score += 10

    # Recruiter Response Rate
    response = row["response_rate"]

    score += response * 40

    return round(score, 2)

In [32]:
semantic_df["behavior_score"] = semantic_df.apply(
    calculate_behavior_score,
    axis=1
)

In [33]:
semantic_df[
    [
        "candidate_id",
        "github_score",
        "response_rate",
        "behavior_score"
    ]
].head()

       candidate_id  github_score  response_rate  behavior_score
99805  CAND_0099806          86.9           0.76            90.4
61264  CAND_0061265          79.8           0.94            87.6
76250  CAND_0076251          -1.0           0.51            50.4
36436  CAND_0036437          35.2           0.87            34.8
45249  CAND_0045250          -1.0           0.74            29.6

In [34]:
def experience_score(exp):

    if 6 <= exp <= 8:
        return 100

    elif 5 <= exp <= 9:
        return 80

    elif 4 <= exp <= 10:
        return 50

    return 10

In [35]:
semantic_df["experience_score"] = semantic_df[
    "experience"
].apply(experience_score)

In [36]:
semantic_df["final_score"] = (

      semantic_df["semantic_score"] * 60

    + semantic_df["behavior_score"] * 0.25

    + semantic_df["experience_score"] * 0.15

)

In [37]:
semantic_df = semantic_df.sort_values(
    by=[
        "final_score",
        "candidate_id"
    ],
    ascending=[
        False,
        True
    ]
)

In [38]:
semantic_df[
    [
        "candidate_id",
        "semantic_score",
        "behavior_score",
        "experience_score",
        "final_score"
    ]
].head(20)

,candidate_id,semantic_score,behavior_score,experience_score,final_score
61264,CAND_0061265,0.675921,87.6,100,77.455252
18721,CAND_0018722,0.652239,91.6,100,77.034338
64325,CAND_0064326,0.655090,87.6,100,76.205412
71973,CAND_0071974,0.640586,90.4,100,76.035143
77336,CAND_0077337,0.645365,88.0,100,75.721909
65194,CAND_0065195,0.664490,92.0,80,74.869419
14439,CAND_0014440,0.629009,85.6,100,74.140555
18498,CAND_0018499,0.628521,84.4,100,73.811258
98845,CAND_0098846,0.623737,84.8,100,73.624225
76162,CAND_0076163,0.586202,93.6,100,73.572112
28792,CAND_0028793,0.629445,82.8,100,73.466705
99805,CAND_0099806,0.714797,90.4,50,72.987798
2024,CAND_0002025,0.631809,92.0,80,72.908554
83306,CAND_0083307,0.638396,78.0,100,72.803780
5648,CAND_0005649,0.616776,82.8,100,72.706565
11686,CAND_0011687,0.601946,85.6,100,72.516768
96141,CAND_0096142,0.618517,93.6,80,72.511034
93911,CAND_0093912,0.638854,86.4,80,71.931234
69904,CAND_0069905,0.650917,71.2,100,71.855027
50875,CAND_0050876,0.585748,86.8,100,71.844855

In [39]:
def generate_reasoning(row):

    reasons = []

    if row["semantic_score"] > 0.60:
        reasons.append(
            "Strong match for retrieval, ranking and search systems"
        )

    elif row["semantic_score"] > 0.50:
        reasons.append(
            "Good semantic alignment with AI Engineer role"
        )

    if row["experience_score"] >= 80:
        reasons.append(
            f"{row['experience']} years relevant experience"
        )

    if row["open_to_work"]:
        reasons.append(
            "Open to work"
        )

    if row["github_score"] > 60:
        reasons.append(
            "Strong GitHub activity"
        )

    if row["response_rate"] > 0.50:
        reasons.append(
            "High recruiter response rate"
        )

    return "; ".join(reasons)

In [40]:
semantic_df["reasoning"] = semantic_df.apply(
    generate_reasoning,
    axis=1
)

In [41]:
top100 = semantic_df.head(100).copy()

In [42]:
top100["rank"] = range(
    1,
    101
)

In [43]:
submission = top100[
    [
        "candidate_id",
        "rank",
        "final_score",
        "reasoning"
    ]
].copy()

In [44]:
submission.rename(
    columns={
        "final_score": "score"
    },
    inplace=True
)

In [45]:
print(
    "Rows:",
    len(submission)
)

print(
    "Unique Candidate IDs:",
    submission["candidate_id"].nunique()
)

print(
    "Unique Ranks:",
    submission["rank"].nunique()
)

Rows: 100
Unique Candidate IDs: 100
Unique Ranks: 100

In [46]:
submission.to_csv(
    "/content/drive/MyDrive/ApnaHireAI/output/submission.csv",
    index=False
)

print(
    "Submission Saved"
)

Submission Saved

In [47]:
print(
    submission.head(10)
)

       candidate_id  rank      score  \
61264  CAND_0061265     1  77.455252
18721  CAND_0018722     2  77.034338
64325  CAND_0064326     3  76.205412
71973  CAND_0071974     4  76.035143
77336  CAND_0077337     5  75.721909
65194  CAND_0065195     6  74.869419
14439  CAND_0014440     7  74.140555
18498  CAND_0018499     8  73.811258
98845  CAND_0098846     9  73.624225
76162  CAND_0076163    10  73.572112

                                               reasoning
61264  Strong match for retrieval, ranking and search...
18721  Strong match for retrieval, ranking and search...
64325  Strong match for retrieval, ranking and search...
71973  Strong match for retrieval, ranking and search...
77336  Strong match for retrieval, ranking and search...
65194  Strong match for retrieval, ranking and search...
14439  Strong match for retrieval, ranking and search...
18498  Strong match for retrieval, ranking and search...
98845  Strong match for retrieval, ranking and search...
76162  Good semantic alignment with AI Engineer role;...

In [48]:
print(
    submission["score"]
    .is_monotonic_decreasing
)

True

In [49]:
submission.head(10)

,candidate_id,rank,score,reasoning
61264,CAND_0061265,1,77.455252,"Strong match for retrieval, ranking and search..."
18721,CAND_0018722,2,77.034338,"Strong match for retrieval, ranking and search..."
64325,CAND_0064326,3,76.205412,"Strong match for retrieval, ranking and search..."
71973,CAND_0071974,4,76.035143,"Strong match for retrieval, ranking and search..."
77336,CAND_0077337,5,75.721909,"Strong match for retrieval, ranking and search..."
65194,CAND_0065195,6,74.869419,"Strong match for retrieval, ranking and search..."
14439,CAND_0014440,7,74.140555,"Strong match for retrieval, ranking and search..."
18498,CAND_0018499,8,73.811258,"Strong match for retrieval, ranking and search..."
98845,CAND_0098846,9,73.624225,"Strong match for retrieval, ranking and search..."
76162,CAND_0076163,10,73.572112,Good semantic alignment with AI Engineer role;...

In [50]:
print(candidates[0].keys())

dict_keys(['candidate_id', 'profile', 'career_history', 'education', 'skills', 'certifications', 'languages', 'redrob_signals'])

In [51]:
career_keywords = [
    "retrieval",
    "ranking",
    "search",
    "recommendation",
    "matching",
    "embeddings",
    "vector",
    "relevance",
    "ndcg",
    "mrr",
    "map",
    "evaluation",
    "hybrid search",
    "vector database"
]

In [52]:
def get_career_score(candidate):

    text = " ".join([
        job["description"]
        for job in candidate["career_history"]
    ]).lower()

    score = 0

    for keyword in career_keywords:

        if keyword in text:
            score += 10

    return min(score, 100)

In [53]:
career_scores = {}

for candidate in candidates:

    career_scores[
        candidate["candidate_id"]
    ] = get_career_score(
        candidate
    )

In [54]:
semantic_df["career_score"] = semantic_df[
    "candidate_id"
].map(career_scores)

In [55]:
semantic_df["final_score"] = (

      semantic_df["semantic_score"] * 100 * 0.50

    + semantic_df["behavior_score"] * 0.20

    + semantic_df["experience_score"] * 0.10

    + semantic_df["career_score"] * 0.20

)

In [56]:
semantic_df = semantic_df.sort_values(
    by=["final_score", "candidate_id"],
    ascending=[False, True]
)

In [57]:
top100 = semantic_df.head(100).copy()

top100["rank"] = range(1, 101)

In [58]:
print(
    semantic_df[
        ["candidate_id", "career_score"]
    ].head(10)
)

       candidate_id  career_score
18498  CAND_0018499            80
77336  CAND_0077337            70
55904  CAND_0055905            90
71973  CAND_0071974            60
46063  CAND_0046064            90
64325  CAND_0064326            50
79386  CAND_0079387            70
28792  CAND_0028793            60
83306  CAND_0083307            60
5648   CAND_0005649            60

In [59]:
candidate_id = "CAND_0086022"

for c in candidates:

    if c["candidate_id"] == candidate_id:

        for job in c["career_history"]:

            print(job["description"])

        break

Built a RAG-based ranking pipeline serving 50M+ queries per month for an internal recruiter-facing search product. The architecture combined BM25 + dense retrieval (BGE embeddings, FAISS HNSW) with an LLM-based re-ranker on the top-50, falling back to a learning-to-rank model when latency budget was tight. Designed the offline evaluation framework from scratch — NDCG, MRR, recall@K calibrated against online A/B engagement metrics. Drove the migration over 4 months including the recruiter-feedback loop that surfaced reranking edge cases.
Led the migration from keyword-based to embedding-based search across a 30M+ candidate corpus over 8 months. Designed three successive ranker variants and ran them in A/B testing alongside the legacy keyword system. The final embedding ranker improved recruiter engagement metrics by 24% and reduced the average time-to-shortlist by 38%. Most of the engineering effort went into the boring infrastructure: index versioning, embedding versioning, rollback paths, and the dashboards that let recruiters trust the new system. Mentored two junior engineers through this rollout.

In [60]:
print(
    candidates[0]["redrob_signals"].keys()
)

dict_keys(['profile_completeness_score', 'signup_date', 'last_active_date', 'open_to_work_flag', 'profile_views_received_30d', 'applications_submitted_30d', 'recruiter_response_rate', 'avg_response_time_hours', 'skill_assessment_scores', 'connection_count', 'endorsements_received', 'notice_period_days', 'expected_salary_range_inr_lpa', 'preferred_work_mode', 'willing_to_relocate', 'github_activity_score', 'search_appearance_30d', 'saved_by_recruiters_30d', 'interview_completion_rate', 'offer_acceptance_rate', 'verified_email', 'verified_phone', 'linkedin_connected'])

In [61]:
def advanced_behavior_score(candidate):

    s = candidate["redrob_signals"]

    score = 0

    # Open to work
    if s["open_to_work_flag"]:
        score += 20

    # Recruiter response
    score += s["recruiter_response_rate"] * 20

    # Interview completion
    score += s["interview_completion_rate"] * 15

    # GitHub
    github = s["github_activity_score"]

    if github > 0:
        score += min(github / 5, 15)

    # Recruiter interest
    score += min(
        s["saved_by_recruiters_30d"] * 2,
        10
    )

    # Search visibility
    score += min(
        s["search_appearance_30d"] / 20,
        10
    )

    # Short notice period
    notice = s["notice_period_days"]

    if notice <= 30:
        score += 10

    elif notice <= 60:
        score += 5

    # Verified profile
    if s["verified_email"]:
        score += 2

    if s["verified_phone"]:
        score += 2

    return round(score, 2)

In [62]:
advanced_scores = {}

for candidate in candidates:

    advanced_scores[
        candidate["candidate_id"]
    ] = advanced_behavior_score(
        candidate
    )

In [63]:
semantic_df["advanced_behavior_score"] = (
    semantic_df["candidate_id"]
    .map(advanced_scores)
)

In [64]:
print(
    semantic_df[
        [
            "candidate_id",
            "advanced_behavior_score"
        ]
    ].head()
)

       candidate_id  advanced_behavior_score
18498  CAND_0018499                    93.20
77336  CAND_0077337                    92.55
55904  CAND_0055905                    81.45
71973  CAND_0071974                    88.55
46063  CAND_0046064                    95.06

In [65]:
semantic_df["final_score"] = (

      semantic_df["semantic_score"] * 100 * 0.45

    + semantic_df["career_score"] * 0.25

    + semantic_df["advanced_behavior_score"] * 0.20

    + semantic_df["experience_score"] * 0.10

)

In [66]:
semantic_df = semantic_df.sort_values(
    by=["final_score", "candidate_id"],
    ascending=[False, True]
)

top100 = semantic_df.head(100).copy()

top100["rank"] = range(1, 101)

In [67]:
print(len(top100))

print(
    top100["candidate_id"]
    .nunique()
)

print(
    top100["rank"]
    .nunique()
)

print(
    top100["final_score"]
    .is_monotonic_decreasing
)

100
100
100
True

In [68]:
submission = top100[
    [
        "candidate_id",
        "rank",
        "final_score",
        "reasoning"
    ]
].copy()

submission.rename(
    columns={
        "final_score": "score"
    },
    inplace=True
)

submission.to_csv(
    "submission.csv",
    index=False
)

print(
    submission.head()
)

       candidate_id  rank      score  \
18498  CAND_0018499     1  76.923443
55904  CAND_0055905     2  76.636426
46063  CAND_0046064     3  76.383319
81845  CAND_0081846     4  75.802562
77336  CAND_0077337     5  75.051431

                                               reasoning
18498  Strong match for retrieval, ranking and search...
55904  Strong match for retrieval, ranking and search...
46063  Good semantic alignment with AI Engineer role;...
81845  Strong match for retrieval, ranking and search...
77336  Strong match for retrieval, ranking and search...

In [69]:
submission.shape

(100, 4)

In [70]:
submission.columns

Index(['candidate_id', 'rank', 'score', 'reasoning'], dtype='object')

In [71]:
print("Rows:", len(submission))
print("Unique IDs:", submission["candidate_id"].nunique())
print("Unique Ranks:", submission["rank"].nunique())
print("Descending Scores:", submission["score"].is_monotonic_decreasing)

Rows: 100
Unique IDs: 100
Unique Ranks: 100
Descending Scores: True

In [72]:
!python "/content/drive/MyDrive/ApnaHireAI/data/validate_submission.py" \
"/content/drive/MyDrive/ApnaHireAI/output/submission.csv"

Submission is valid.